#!/usr/bin/env Rscript

############################################################
## 92_pre_submission_sensitivity_checks_PIPELINE_OBJECTS_FAST.R
##
## Standalone pre-submission sensitivity checks using the same
## objects generated by the modular ROSMAP main-figure pipeline.
##
## FAST version: avoids expensive within-stage permutation loops by
## default, uses vectorized stage residualization, precomputes matched
## samplers, and defaults to 1,000 permutations for first-pass runs.
##
## Run location:
##   Put this file in the same folder as 00_config.R through
##   07_build_matched_null_objects.R, then source/run it from R.
##
## What this checks:
##   CHECK 1. Stage-residualized / within-stage Hsp60/10 client
##            co-movement.
##   CHECK 2. Function-matched Hsp60/10 client vs non-client
##            mitochondrial vulnerability.
##
## GitHub safety:
##   This script does not call git, git add, git commit, or git push.
##   It writes local aggregated outputs only, by default under:
##     file.path(cfg$output_root, "pre_submission_sensitivity_checks")
##   Do not commit these outputs unless you intentionally decide to.
############################################################

suppressPackageStartupMessages({
  library(tidyverse)
  library(broom)
})

sensitivity_seed <- 1300L
set.seed(sensitivity_seed)
options(stringsAsFactors = FALSE)

`%||%` <- function(x, y) {
  if (is.null(x) || length(x) == 0 || all(is.na(x))) y else x
}

############################################################
## 0. Locate scripts and source config/helpers
############################################################

this_file <- tryCatch(
  normalizePath(sys.frame(1)$ofile, mustWork = TRUE),
  error = function(e) NA_character_
)

if (is.na(this_file) && requireNamespace("rstudioapi", quietly = TRUE)) {
  this_file <- tryCatch(
    normalizePath(rstudioapi::getActiveDocumentContext()$path, mustWork = TRUE),
    error = function(e) NA_character_
  )
}

## Resolve the R pipeline directory deterministically.
##
## When R/92 is sourced from a validator, sys.frame(1)$ofile can refer to
## the caller rather than this script. Therefore do not use `ofile` to choose
## the working directory. Prefer the repository root/current R directory,
## then fall back to cfg$project_dir if cfg is already loaded.

wd_now <- normalizePath(getwd(), mustWork = TRUE)

if (
  file.exists(file.path(wd_now, "R", "00_config.R")) &&
  file.exists(file.path(wd_now, "R", "01_utils.R"))
) {
  script_dir <- normalizePath(file.path(wd_now, "R"), mustWork = TRUE)
} else if (
  file.exists(file.path(wd_now, "00_config.R")) &&
  file.exists(file.path(wd_now, "01_utils.R"))
) {
  script_dir <- wd_now
} else if (
  exists("cfg", envir = .GlobalEnv, inherits = FALSE) &&
  !is.null(cfg$project_dir) &&
  file.exists(file.path(cfg$project_dir, "R", "00_config.R")) &&
  file.exists(file.path(cfg$project_dir, "R", "01_utils.R"))
) {
  script_dir <- normalizePath(
    file.path(cfg$project_dir, "R"),
    mustWork = TRUE
  )
} else {
  stop(
    "Could not locate the R pipeline directory. ",
    "Run this from the repository root or from the R/ directory.",
    call. = FALSE
  )
}

old_wd <- getwd()
setwd(script_dir)
on.exit(setwd(old_wd), add = TRUE)

message("Script directory: ", getwd())

for (script in c("00_config.R", "01_utils.R")) {
  script_path <- file.path(script_dir, script)

  if (!file.exists(script_path)) {
    stop(
      "Missing required pipeline script: ",
      script_path,
      call. = FALSE
    )
  }

  source(script_path, local = .GlobalEnv)
}

sens_bool <- function(name, default = "TRUE") {
  tolower(Sys.getenv(name, default)) %in% c("true", "t", "1", "yes", "y")
}

sens_int <- function(name, default) {
  out <- suppressWarnings(as.integer(Sys.getenv(name, as.character(default))))
  if (!is.finite(out) || is.na(out) || out < 0) default else out
}

sens_cfg <- list(
  output_dir = Sys.getenv(
    "SENSITIVITY_OUTPUT_DIR",
    file.path(cfg$output_root, "pre_submission_sensitivity_checks")
  ),
  ## Fast default for interactive testing. For final archival runs, set
  ## SENSITIVITY_N_PERM=10000 or set check-specific values below.
  n_perm = sens_int("SENSITIVITY_N_PERM", 1000),
  n_perm_check1 = sens_int("SENSITIVITY_N_PERM_CHECK1", sens_int("SENSITIVITY_N_PERM", 1000)),
  n_perm_check2 = sens_int("SENSITIVITY_N_PERM_CHECK2", sens_int("SENSITIVITY_N_PERM", 1000)),
  top_n_late_decline = sens_int("SENSITIVITY_TOP_N_LATE_DECLINE", 40),
  min_selected_genes = sens_int("SENSITIVITY_MIN_SELECTED_GENES", 8),
  min_clients_per_module = sens_int("SENSITIVITY_MIN_CLIENTS_PER_MODULE", 3),
  min_nonclients_per_module = sens_int("SENSITIVITY_MIN_NONCLIENTS_PER_MODULE", 3),
  corr_method = Sys.getenv("SENSITIVITY_CORR_METHOD", "spearman"),
  run_check1 = sens_bool("SENSITIVITY_RUN_CHECK1", "TRUE"),
  run_check2 = sens_bool("SENSITIVITY_RUN_CHECK2", "TRUE"),
  ## This is the main speed lever. Observed within-stage correlations are
  ## still written, but permutation nulls within each stage are skipped by default.
  run_within_stage_nulls = sens_bool("SENSITIVITY_WITHIN_STAGE_NULLS", "FALSE"),
  write_full_null_distributions = sens_bool("SENSITIVITY_WRITE_FULL_NULL_DISTRIBUTIONS", "FALSE"),
  save_plots = sens_bool("SENSITIVITY_SAVE_PLOTS", "TRUE"),
  progress_every = sens_int("SENSITIVITY_PROGRESS_EVERY", 100),
  source_upstream_if_missing = sens_bool("SENSITIVITY_SOURCE_UPSTREAM_IF_MISSING", "TRUE")
)

dir.create(sens_cfg$output_dir, recursive = TRUE, showWarnings = FALSE)
message("Sensitivity output directory: ", sens_cfg$output_dir)
message("Check 1 permutations: ", sens_cfg$n_perm_check1)
message("Check 2 permutations: ", sens_cfg$n_perm_check2)
message("Within-stage permutation nulls: ", sens_cfg$run_within_stage_nulls)

############################################################
## 1. Load required pipeline objects, sourcing upstream only if needed
############################################################

obj_path <- function(name) file.path(cfg$object_dir, paste0(name, ".rds"))
table_path <- function(name) file.path(cfg$table_dir, paste0(name, ".csv"))

load_obj_if_needed <- function(name, assign_as = name, required = TRUE) {
  if (exists(assign_as, envir = .GlobalEnv, inherits = FALSE)) {
    return(get(assign_as, envir = .GlobalEnv, inherits = FALSE))
  }
  path <- obj_path(name)
  if (file.exists(path)) {
    x <- readRDS(path)
    assign(assign_as, x, envir = .GlobalEnv)
    message("Loaded object from RDS: ", assign_as, " <- ", path)
    return(x)
  }
  if (isTRUE(required)) {
    stop("Missing required object/RDS: ", name, " at ", path, call. = FALSE)
  }
  NULL
}

try_load_existing_outputs <- function() {
  invisible(lapply(c(
    "prot_mat_adj", "prot_meta_adj", "protein_covars",
    "all_hsp60_10_client_tbl", "priority_tbl", "pathway_gene_sets",
    "all_hsp60_10_clients"
  ), function(nm) load_obj_if_needed(nm, required = FALSE)))

  if (exists("prot_mat_adj", envir = .GlobalEnv, inherits = FALSE) &&
      !exists("prot_mat", envir = .GlobalEnv, inherits = FALSE)) {
    assign("prot_mat", get("prot_mat_adj", envir = .GlobalEnv), envir = .GlobalEnv)
  }

  null_input_csv <- table_path("figure5_null_input_COVARIATE_ADJUSTED")
  if (!exists("null_input_tbl", envir = .GlobalEnv, inherits = FALSE) && file.exists(null_input_csv)) {
    assign("null_input_tbl", readr::read_csv(null_input_csv, show_col_types = FALSE), envir = .GlobalEnv)
    message("Loaded null_input_tbl from CSV: ", null_input_csv)
  }
}

required_for_checks <- c(
  "prot_mat", "prot_meta_adj", "all_hsp60_10_client_tbl",
  "priority_tbl", "pathway_gene_sets", "null_input_tbl"
)

try_load_existing_outputs()
missing_now <- required_for_checks[!vapply(required_for_checks, exists, logical(1), envir = .GlobalEnv)]

if (length(missing_now) > 0 && isTRUE(sens_cfg$source_upstream_if_missing)) {
  message("Missing upstream object(s): ", paste(missing_now, collapse = ", "))
  message("Sourcing 02-07 to rebuild required objects...")
  for (script in c(
    "02_load_data.R",
    "03_build_adjusted_core_objects.R",
    "04_build_pathway_sets_all_clients.R",
    "05_build_adjusted_all_client_tables.R",
    "06_build_cognition_objects.R",
    "07_build_matched_null_objects.R"
  )) {
    if (!file.exists(script)) stop("Missing required upstream script: ", script, call. = FALSE)
    source(script, local = .GlobalEnv)
  }
}

missing_final <- required_for_checks[!vapply(required_for_checks, exists, logical(1), envir = .GlobalEnv)]
if (length(missing_final) > 0) {
  stop(
    "Still missing required object(s): ", paste(missing_final, collapse = ", "),
    "\nRun the modular pipeline through 07_build_matched_null_objects.R first, ",
    "or leave SENSITIVITY_SOURCE_UPSTREAM_IF_MISSING=TRUE.",
    call. = FALSE
  )
}

############################################################
## 2. Shared helpers
############################################################

safe_num2 <- function(x) suppressWarnings(as.numeric(x))

safe_mean <- function(x) {
  x <- x[is.finite(x)]
  if (length(x) == 0) return(NA_real_)
  mean(x)
}

safe_median <- function(x) {
  x <- x[is.finite(x)]
  if (length(x) == 0) return(NA_real_)
  median(x)
}

empirical_p_greater <- function(null_values, observed) {
  null_values <- null_values[is.finite(null_values)]
  if (length(null_values) == 0 || !is.finite(observed)) return(NA_real_)
  (1 + sum(null_values >= observed)) / (length(null_values) + 1)
}

safe_wilcox_greater <- function(x, y) {
  x <- x[is.finite(x)]
  y <- y[is.finite(y)]
  if (length(x) < 2 || length(y) < 2) return(NA_real_)
  out <- tryCatch(
    suppressWarnings(stats::wilcox.test(x, y, alternative = "greater", exact = FALSE)$p.value),
    error = function(e) NA_real_
  )
  out
}

normalize_stage <- function(x) {
  x <- as.character(x)
  dplyr::case_when(
    x %in% c("NCI", "MCI", "AD") ~ x,
    TRUE ~ NA_character_
  )
}

pairwise_cor_summary <- function(cor_mat, genes, label = NA_character_) {
  genes <- intersect(unique(genes), rownames(cor_mat))
  genes <- intersect(genes, colnames(cor_mat))

  if (length(genes) < 3) {
    return(tibble(
      set_label = label,
      n_genes = length(genes),
      n_pairs = 0L,
      mean_r = NA_real_,
      median_r = NA_real_,
      mean_abs_r = NA_real_,
      median_abs_r = NA_real_,
      mean_fisher_z = NA_real_
    ))
  }

  vals <- cor_mat[genes, genes, drop = FALSE]
  vals <- vals[upper.tri(vals)]
  vals <- vals[is.finite(vals)]
  vals_clip <- pmin(pmax(vals, -0.999999), 0.999999)

  tibble(
    set_label = label,
    n_genes = length(genes),
    n_pairs = length(vals),
    mean_r = safe_mean(vals),
    median_r = safe_median(vals),
    mean_abs_r = safe_mean(abs(vals)),
    median_abs_r = safe_median(abs(vals)),
    mean_fisher_z = safe_mean(atanh(vals_clip))
  )
}

progress_msg <- function(i, n, label) {
  if (n <= 0) return(invisible(NULL))
  if (i == 1 || i == n || (sens_cfg$progress_every > 0 && i %% sens_cfg$progress_every == 0)) {
    message(label, ": ", i, "/", n, " iterations")
  }
  invisible(NULL)
}

make_strata_key <- function(df, cols) {
  if (length(cols) == 0) return(rep("ALL", nrow(df)))
  vals <- lapply(cols, function(cc) {
    v <- as.character(df[[cc]])
    v[is.na(v)] <- "MISSING"
    v
  })
  do.call(paste, c(vals, sep = "\r"))
}

unique_col_sets <- function(x) {
  keep <- !duplicated(vapply(x, function(z) paste(z, collapse = "\r"), character(1)))
  x[keep]
}

select_viable_match_cols <- function(selected_tbl, pool_tbl, try_cols_list, replace = FALSE) {
  try_cols_list <- unique_col_sets(try_cols_list)

  for (cols in try_cols_list) {
    if (length(cols) > 0 && (!all(cols %in% names(selected_tbl)) || !all(cols %in% names(pool_tbl)))) next

    selected_keys <- make_strata_key(selected_tbl, cols)
    pool_keys <- make_strata_key(pool_tbl, cols)
    selected_counts <- table(selected_keys)
    pool_counts <- table(pool_keys)

    if (length(selected_counts) == 0 || length(pool_counts) == 0) next
    if (!all(names(selected_counts) %in% names(pool_counts))) next

    available <- as.integer(pool_counts[names(selected_counts)])
    needed <- as.integer(selected_counts)

    ok <- if (isTRUE(replace)) all(available > 0) else all(available >= needed)
    if (isTRUE(ok)) return(cols)
  }

  NULL
}

build_fast_gene_sampler <- function(selected_tbl, pool_tbl, try_cols_list) {
  selected_tbl <- selected_tbl |> dplyr::filter(!is.na(gene), gene != "") |> dplyr::distinct(gene, .keep_all = TRUE)
  pool_tbl <- pool_tbl |> dplyr::filter(!is.na(gene), gene != "") |> dplyr::distinct(gene, .keep_all = TRUE)

  cols <- select_viable_match_cols(selected_tbl, pool_tbl, try_cols_list, replace = FALSE)
  if (is.null(cols)) {
    stop("Could not build a matched gene sampler without replacement. Try lowering selected-set size or matching constraints.", call. = FALSE)
  }

  selected_keys <- make_strata_key(selected_tbl, cols)
  pool_keys <- make_strata_key(pool_tbl, cols)
  needed <- table(selected_keys)
  pool_genes <- split(pool_tbl$gene, pool_keys)

  force(needed)
  force(pool_genes)
  force(cols)

  list(
    matched_on = if (length(cols) == 0) "none" else paste(cols, collapse = ";"),
    sampler = function() {
      unlist(lapply(names(needed), function(k) {
        sample(pool_genes[[k]], size = as.integer(needed[[k]]), replace = FALSE)
      }), use.names = FALSE)
    }
  )
}

build_fast_row_sampler <- function(selected_tbl, pool_tbl, try_cols_list) {
  selected_tbl <- selected_tbl |> dplyr::filter(!is.na(gene), gene != "")
  pool_tbl <- pool_tbl |> dplyr::filter(!is.na(gene), gene != "")

  cols <- select_viable_match_cols(selected_tbl, pool_tbl, try_cols_list, replace = TRUE)
  if (is.null(cols)) {
    stop("Could not build a matched row sampler. Try lowering matching constraints.", call. = FALSE)
  }

  selected_keys <- make_strata_key(selected_tbl, cols)
  pool_keys <- make_strata_key(pool_tbl, cols)
  needed <- table(selected_keys)
  pool_rows <- split(seq_len(nrow(pool_tbl)), pool_keys)

  force(needed)
  force(pool_rows)
  force(cols)
  force(pool_tbl)

  list(
    matched_on = if (length(cols) == 0) "none" else paste(cols, collapse = ";"),
    sampler = function() {
      idx <- unlist(lapply(names(needed), function(k) {
        candidates <- pool_rows[[k]]
        sample(candidates, size = as.integer(needed[[k]]), replace = length(candidates) < as.integer(needed[[k]]))
      }), use.names = FALSE)
      pool_tbl[idx, , drop = FALSE]
    }
  )
}

write_null_outputs <- function(null_tbl, full_file, summary_file) {
  if (isTRUE(sens_cfg$write_full_null_distributions)) {
    readr::write_csv(null_tbl, full_file)
  }

  null_summary <- null_tbl |>
    dplyr::group_by(dplyr::across(dplyr::any_of(c("context", "selection", "group", "metric")))) |>
    dplyr::summarise(
      n_iter = dplyr::n(),
      mean_abs_r_mean = if ("mean_abs_r" %in% names(dplyr::pick(dplyr::everything()))) mean(mean_abs_r, na.rm = TRUE) else NA_real_,
      mean_abs_r_q025 = if ("mean_abs_r" %in% names(dplyr::pick(dplyr::everything()))) stats::quantile(mean_abs_r, 0.025, na.rm = TRUE) else NA_real_,
      mean_abs_r_q500 = if ("mean_abs_r" %in% names(dplyr::pick(dplyr::everything()))) stats::quantile(mean_abs_r, 0.500, na.rm = TRUE) else NA_real_,
      mean_abs_r_q975 = if ("mean_abs_r" %in% names(dplyr::pick(dplyr::everything()))) stats::quantile(mean_abs_r, 0.975, na.rm = TRUE) else NA_real_,
      null_mean_value = if ("null_value" %in% names(dplyr::pick(dplyr::everything()))) mean(null_value, na.rm = TRUE) else NA_real_,
      null_q025 = if ("null_value" %in% names(dplyr::pick(dplyr::everything()))) stats::quantile(null_value, 0.025, na.rm = TRUE) else NA_real_,
      null_q500 = if ("null_value" %in% names(dplyr::pick(dplyr::everything()))) stats::quantile(null_value, 0.500, na.rm = TRUE) else NA_real_,
      null_q975 = if ("null_value" %in% names(dplyr::pick(dplyr::everything()))) stats::quantile(null_value, 0.975, na.rm = TRUE) else NA_real_,
      .groups = "drop"
    )
  readr::write_csv(null_summary, summary_file)
  invisible(null_summary)
}

sample_matched_genes <- function(selected_tbl, pool_tbl, match_cols) {
  selected_tbl <- selected_tbl |> dplyr::filter(!is.na(gene), gene != "")
  pool_tbl <- pool_tbl |> dplyr::filter(!is.na(gene), gene != "") |> dplyr::distinct(gene, .keep_all = TRUE)
  n_needed <- nrow(selected_tbl)

  try_cols_list <- list(
    match_cols,
    intersect(match_cols, c("functional_class", "abundance_bin")),
    intersect(match_cols, "functional_class"),
    intersect(match_cols, "abundance_bin"),
    character()
  )
  try_cols_list <- unique(try_cols_list)

  for (cols in try_cols_list) {
    if (length(cols) == 0) {
      if (nrow(pool_tbl) >= n_needed) return(sample(pool_tbl$gene, n_needed, replace = FALSE))
      next
    }

    if (!all(cols %in% names(selected_tbl)) || !all(cols %in% names(pool_tbl))) next

    selected_counts <- selected_tbl |>
      dplyr::mutate(dplyr::across(dplyr::all_of(cols), ~replace_na(as.character(.x), "MISSING"))) |>
      dplyr::count(dplyr::across(dplyr::all_of(cols)), name = "n_needed")

    pool_counts <- pool_tbl |>
      dplyr::mutate(dplyr::across(dplyr::all_of(cols), ~replace_na(as.character(.x), "MISSING"))) |>
      dplyr::count(dplyr::across(dplyr::all_of(cols)), name = "n_available")

    ok <- selected_counts |>
      dplyr::left_join(pool_counts, by = cols) |>
      dplyr::mutate(n_available = replace_na(n_available, 0L)) |>
      dplyr::summarise(ok = all(n_available >= n_needed), .groups = "drop") |>
      dplyr::pull(ok)

    if (!isTRUE(ok)) next

    sampled <- selected_counts |>
      dplyr::group_split(dplyr::across(dplyr::all_of(cols))) |>
      purrr::map(function(stratum_row) {
        cond <- rep(TRUE, nrow(pool_tbl))
        for (cc in cols) {
          selected_val <- replace_na(as.character(stratum_row[[cc]][1]), "MISSING")
          pool_val <- replace_na(as.character(pool_tbl[[cc]]), "MISSING")
          cond <- cond & pool_val == selected_val
        }
        sample(pool_tbl$gene[cond], stratum_row$n_needed[1], replace = FALSE)
      }) |>
      unlist(use.names = FALSE)

    return(sampled)
  }

  stop("Could not sample a matched gene set without replacement. Try lowering selected-set size.", call. = FALSE)
}

sample_matched_rows_with_replacement <- function(selected_tbl, pool_tbl, match_cols) {
  selected_tbl <- selected_tbl |> dplyr::filter(!is.na(gene), gene != "")
  pool_tbl <- pool_tbl |> dplyr::filter(!is.na(gene), gene != "")

  try_cols_list <- list(
    match_cols,
    intersect(match_cols, c("functional_module", "abundance_bin")),
    intersect(match_cols, "functional_module"),
    intersect(match_cols, "abundance_bin"),
    character()
  )
  try_cols_list <- unique(try_cols_list)

  for (cols in try_cols_list) {
    if (length(cols) == 0) {
      if (nrow(pool_tbl) == 0) next
      return(pool_tbl[sample(seq_len(nrow(pool_tbl)), nrow(selected_tbl), replace = nrow(pool_tbl) < nrow(selected_tbl)), , drop = FALSE])
    }

    if (!all(cols %in% names(selected_tbl)) || !all(cols %in% names(pool_tbl))) next

    selected_counts <- selected_tbl |>
      dplyr::mutate(dplyr::across(dplyr::all_of(cols), ~replace_na(as.character(.x), "MISSING"))) |>
      dplyr::count(dplyr::across(dplyr::all_of(cols)), name = "n_needed")

    pool_counts <- pool_tbl |>
      dplyr::mutate(dplyr::across(dplyr::all_of(cols), ~replace_na(as.character(.x), "MISSING"))) |>
      dplyr::count(dplyr::across(dplyr::all_of(cols)), name = "n_available")

    possible <- selected_counts |>
      dplyr::left_join(pool_counts, by = cols) |>
      dplyr::mutate(n_available = replace_na(n_available, 0L)) |>
      dplyr::summarise(ok = all(n_available > 0), .groups = "drop") |>
      dplyr::pull(ok)

    if (!isTRUE(possible)) next

    sampled <- selected_counts |>
      dplyr::group_split(dplyr::across(dplyr::all_of(cols))) |>
      purrr::map_dfr(function(stratum_row) {
        cond <- rep(TRUE, nrow(pool_tbl))
        for (cc in cols) {
          selected_val <- replace_na(as.character(stratum_row[[cc]][1]), "MISSING")
          pool_val <- replace_na(as.character(pool_tbl[[cc]]), "MISSING")
          cond <- cond & pool_val == selected_val
        }
        candidates <- pool_tbl[cond, , drop = FALSE]
        candidates[sample(seq_len(nrow(candidates)), stratum_row$n_needed[1], replace = nrow(candidates) < stratum_row$n_needed[1]), , drop = FALSE]
      })

    return(sampled)
  }

  stop("Could not sample matched non-client rows.", call. = FALSE)
}

############################################################
## 3. Build analysis inputs from pipeline objects
############################################################

client_metrics <- all_hsp60_10_client_tbl |>
  dplyr::filter(detected_in_protein) |>
  dplyr::transmute(
    gene = as.character(gene),
    display_gene = as.character(display_gene),
    functional_class = as.character(functional_class),
    protein_late_effect = safe_num2(protein_late_effect),
    protein_late_decline_magnitude = safe_num2(protein_late_decline_magnitude),
    late_decline_percentile = safe_num2(late_decline_percentile),
    hub_mean_abs_cor = safe_num2(hub_mean_abs_cor),
    hub_degree = safe_num2(hub_degree),
    centrality_percentile = safe_num2(centrality_percentile),
    inverse_braak_magnitude = safe_num2(inverse_braak_magnitude),
    inverse_braak_percentile = safe_num2(inverse_braak_percentile),
    agora_target = as.integer(agora_target %||% 0)
  ) |>
  dplyr::left_join(
    null_input_tbl |>
      dplyr::transmute(
        gene = as.character(gene),
        matching_abundance = safe_num2(matching_abundance),
        abundance_bin = as.character(abundance_bin)
      ) |>
      dplyr::distinct(gene, .keep_all = TRUE),
    by = "gene"
  ) |>
  dplyr::mutate(
    abundance_bin = dplyr::if_else(
      is.na(abundance_bin) & is.finite(matching_abundance),
      paste0("bin_", dplyr::ntile(matching_abundance, 10)),
      abundance_bin
    )
  )

readr::write_csv(client_metrics, file.path(sens_cfg$output_dir, "check_inputs_detected_client_metrics.csv"))

message("Detected Hsp60/10 client proteins available for sensitivity checks: ", nrow(client_metrics))

############################################################
## 4. CHECK 1: Stage-residualized / within-stage co-movement
############################################################

make_protein_stage_meta <- function() {
  if (!"clinical_stage" %in% colnames(prot_meta_adj)) {
    stop(
      "prot_meta_adj is missing canonical clinical_stage. ",
      "Run the corrected production pipeline before R/92.",
      call. = FALSE
    )
  }

  out <- prot_meta_adj |>
    dplyr::transmute(
      SampleID = as.character(.data$SampleID),
      stage = normalize_stage(.data$clinical_stage),
      stage = factor(stage, levels = c("NCI", "MCI", "AD"))
    ) |>
    dplyr::filter(
      !is.na(.data$SampleID),
      !is.na(.data$stage),
      .data$SampleID %in% colnames(prot_mat)
    ) |>
    dplyr::distinct(.data$SampleID, .keep_all = TRUE)

  stage_counts <- out |>
    dplyr::count(.data$stage, name = "n_samples") |>
    tidyr::complete(
      stage = factor(c("NCI", "MCI", "AD"), levels = c("NCI", "MCI", "AD")),
      fill = list(n_samples = 0L)
    )

  expected_counts <- c(NCI = 168L, MCI = 97L, AD = 109L)
  observed_counts <- stats::setNames(
    stage_counts$n_samples,
    as.character(stage_counts$stage)
  )

  if (!identical(
    as.integer(observed_counts[names(expected_counts)]),
    as.integer(expected_counts)
  )) {
    stop(
      "Unexpected primary-stage protein sample counts in R/92. Observed: ",
      paste(
        names(observed_counts),
        observed_counts,
        sep = "=",
        collapse = ", "
      ),
      "; expected NCI=168, MCI=97, AD=109.",
      call. = FALSE
    )
  }

  readr::write_csv(
    stage_counts,
    file.path(
      sens_cfg$output_dir,
      "check1_primary_clinical_stage_sample_counts.csv"
    )
  )

  out
}

residualize_matrix_on_stage <- function(mat, stage_meta) {
  ## y ~ stage residuals are equivalent to subtracting the within-stage
  ## gene mean. This vectorized implementation is much faster than fitting
  ## one lm() per protein.
  sample_ids <- intersect(colnames(mat), stage_meta$SampleID)
  stage_meta <- stage_meta[match(sample_ids, stage_meta$SampleID), , drop = FALSE]
  mat <- mat[, sample_ids, drop = FALSE]
  mat <- as.matrix(mat)
  mode(mat) <- "numeric"

  out <- matrix(NA_real_, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  for (stg in levels(stage_meta$stage)) {
    idx <- which(stage_meta$stage == stg)
    if (length(idx) < 2) next
    mu <- rowMeans(mat[, idx, drop = FALSE], na.rm = TRUE)
    out[, idx] <- sweep(mat[, idx, drop = FALSE], 1, mu, FUN = "-")
  }

  out[rowSums(is.finite(out)) < 10, ] <- NA_real_
  out
}

make_cor_mat <- function(mat, method = sens_cfg$corr_method) {
  suppressWarnings(stats::cor(t(mat), use = "pairwise.complete.obs", method = method))
}

select_check1_sets <- function(client_metrics) {
  cm <- client_metrics |>
    dplyr::filter(is.finite(protein_late_decline_magnitude), gene %in% rownames(prot_mat)) |>
    dplyr::arrange(dplyr::desc(protein_late_decline_magnitude))

  n_top <- min(sens_cfg$top_n_late_decline, nrow(cm))
  top_late_decline <- cm |>
    dplyr::slice_head(n = n_top) |>
    dplyr::mutate(selection = "top_late_decline_clients")

  high_both <- cm |>
    dplyr::filter(late_decline_percentile >= 75, centrality_percentile >= 75)

  if (nrow(high_both) >= sens_cfg$min_selected_genes) {
    late_decline_central <- high_both |>
      dplyr::arrange(dplyr::desc(late_decline_percentile + centrality_percentile)) |>
      dplyr::mutate(selection = "late_decline_top_quartile_and_centrality_top_quartile")
  } else {
    late_decline_central <- cm |>
      dplyr::filter(is.finite(centrality_percentile)) |>
      dplyr::mutate(rank_sum = late_decline_percentile + centrality_percentile) |>
      dplyr::arrange(dplyr::desc(rank_sum)) |>
      dplyr::slice_head(n = n_top) |>
      dplyr::mutate(selection = "top_combined_late_decline_and_centrality_rank")
  }

  list(
    top_late_decline_clients = top_late_decline,
    late_decline_central_clients = late_decline_central
  )
}

run_comovement_null <- function(cor_mat, selected_tbl, pool_tbl, label, context) {
  selected_tbl <- selected_tbl |> dplyr::filter(gene %in% rownames(cor_mat), gene %in% colnames(cor_mat))
  pool_tbl <- pool_tbl |>
    dplyr::filter(gene %in% rownames(cor_mat), gene %in% colnames(cor_mat), !gene %in% selected_tbl$gene)

  if (nrow(selected_tbl) < sens_cfg$min_selected_genes) {
    return(list(
      summary = tibble(
        context = context,
        selection = label,
        n_genes = nrow(selected_tbl),
        error = "Too few selected genes after matrix overlap"
      ),
      null = tibble()
    ))
  }

  match_cols <- c("functional_class", "abundance_bin")
  match_cols <- match_cols[vapply(match_cols, function(cc) cc %in% names(client_metrics) && any(!is.na(client_metrics[[cc]])), logical(1))]
  try_cols_list <- list(
    match_cols,
    intersect(match_cols, c("functional_class", "abundance_bin")),
    intersect(match_cols, "functional_class"),
    intersect(match_cols, "abundance_bin"),
    character()
  )

  obs <- pairwise_cor_summary(cor_mat, selected_tbl$gene, label = label)
  sampler_info <- build_fast_gene_sampler(selected_tbl, pool_tbl, try_cols_list)

  n_iter <- sens_cfg$n_perm_check1
  null_stats <- vector("list", n_iter)
  for (i in seq_len(n_iter)) {
    progress_msg(i, n_iter, paste0("CHECK 1 ", context, " / ", label))
    sampled <- sampler_info$sampler()
    null_stats[[i]] <- pairwise_cor_summary(cor_mat, sampled, label = label) |>
      dplyr::mutate(iter = i)
  }
  null <- dplyr::bind_rows(null_stats)

  summary <- obs |>
    dplyr::mutate(
      context = context,
      selection = label,
      null_mean_abs_r = mean(null$mean_abs_r, na.rm = TRUE),
      null_sd_abs_r = stats::sd(null$mean_abs_r, na.rm = TRUE),
      delta_mean_abs_r = mean_abs_r - null_mean_abs_r,
      empirical_p_abs_r_greater = empirical_p_greater(null$mean_abs_r, mean_abs_r),
      null_mean_r = mean(null$mean_r, na.rm = TRUE),
      null_sd_r = stats::sd(null$mean_r, na.rm = TRUE),
      delta_mean_r = mean_r - null_mean_r,
      empirical_p_mean_r_greater = empirical_p_greater(null$mean_r, mean_r),
      n_perm = n_iter,
      corr_method = sens_cfg$corr_method,
      matched_on = sampler_info$matched_on,
      error = NA_character_
    )

  list(summary = summary, null = null)
}

run_check1 <- function() {
  message("\nCHECK 1: stage-residualized / within-stage co-movement")

  stage_meta <- make_protein_stage_meta()
  genes <- intersect(client_metrics$gene, rownames(prot_mat))
  mat_client <- prot_mat[genes, stage_meta$SampleID, drop = FALSE]

  resid_mat <- residualize_matrix_on_stage(mat_client, stage_meta)
  cor_resid <- make_cor_mat(resid_mat)

  selected_sets <- select_check1_sets(client_metrics)
  pool_tbl <- client_metrics |> dplyr::filter(gene %in% genes)

  selected_audit <- purrr::imap_dfr(selected_sets, function(tbl, nm) {
    tbl |> dplyr::mutate(selection_name = nm, .before = 1)
  })
  readr::write_csv(selected_audit, file.path(sens_cfg$output_dir, "check1_selected_client_sets.csv"))

  residual_results <- purrr::imap(selected_sets, function(tbl, nm) {
    run_comovement_null(cor_resid, tbl, pool_tbl, nm, context = "stage_residualized_all_samples")
  })

  residual_summary <- purrr::map_dfr(residual_results, "summary")
  residual_null <- purrr::imap_dfr(residual_results, function(x, nm) {
    x$null |> dplyr::mutate(selection = nm, context = "stage_residualized_all_samples")
  })

  readr::write_csv(residual_summary, file.path(sens_cfg$output_dir, "check1_stage_residualized_comovement_summary.csv"))
  write_null_outputs(
    residual_null,
    full_file = file.path(sens_cfg$output_dir, "check1_stage_residualized_null_distributions.csv"),
    summary_file = file.path(sens_cfg$output_dir, "check1_stage_residualized_null_distribution_summary.csv")
  )

  within_stage_summary <- purrr::map_dfr(levels(stage_meta$stage), function(stg) {
    sample_ids <- stage_meta |> dplyr::filter(stage == stg) |> dplyr::pull(SampleID)
    if (length(sample_ids) < 20) return(tibble())
    cor_stage <- make_cor_mat(mat_client[, sample_ids, drop = FALSE])

    if (isTRUE(sens_cfg$run_within_stage_nulls)) {
      purrr::imap_dfr(selected_sets, function(tbl, nm) {
        run_comovement_null(cor_stage, tbl, pool_tbl, nm, context = paste0("within_stage_", gsub(" ", "_", stg)))$summary |>
          dplyr::mutate(stage = as.character(stg), n_samples = length(sample_ids), nulls_run = TRUE)
      })
    } else {
      purrr::imap_dfr(selected_sets, function(tbl, nm) {
        pairwise_cor_summary(cor_stage, tbl$gene, label = nm) |>
          dplyr::mutate(
            context = paste0("within_stage_", gsub(" ", "_", stg)),
            selection = nm,
            stage = as.character(stg),
            n_samples = length(sample_ids),
            nulls_run = FALSE,
            note = "Observed within-stage co-movement only; set SENSITIVITY_WITHIN_STAGE_NULLS=TRUE for permutation nulls."
          )
      })
    }
  })
  readr::write_csv(within_stage_summary, file.path(sens_cfg$output_dir, "check1_within_stage_comovement_summary.csv"))

  client_cor <- cor_resid[genes, genes, drop = FALSE]
  residual_degree <- purrr::map_dfr(genes, function(g) {
    vals <- client_cor[g, setdiff(genes, g)]
    vals <- vals[is.finite(vals)]
    tibble::tibble(
      gene = g,
      residual_mean_abs_r_to_other_clients = safe_mean(abs(vals)),
      residual_median_abs_r_to_other_clients = safe_median(abs(vals)),
      residual_mean_r_to_other_clients = safe_mean(vals),
      residual_positive_fraction = safe_mean(vals > 0)
    )
  }) |>
    dplyr::left_join(client_metrics, by = "gene")

  residual_centrality_tests <- tibble::tibble(
    predictor = c("protein_late_decline_magnitude", "late_decline_percentile", "hub_mean_abs_cor", "centrality_percentile"),
    outcome = "residual_mean_abs_r_to_other_clients"
  ) |>
    dplyr::mutate(
      n = purrr::map_int(predictor, function(pred) {
        sum(is.finite(residual_degree[[pred]]) & is.finite(residual_degree$residual_mean_abs_r_to_other_clients))
      }),
      spearman_rho = purrr::map_dbl(predictor, function(pred) {
        ok <- is.finite(residual_degree[[pred]]) & is.finite(residual_degree$residual_mean_abs_r_to_other_clients)
        if (sum(ok) < 10) return(NA_real_)
        unname(suppressWarnings(stats::cor(residual_degree[[pred]][ok], residual_degree$residual_mean_abs_r_to_other_clients[ok], method = "spearman")))
      }),
      p_value = purrr::map_dbl(predictor, function(pred) {
        ok <- is.finite(residual_degree[[pred]]) & is.finite(residual_degree$residual_mean_abs_r_to_other_clients)
        if (sum(ok) < 10) return(NA_real_)
        suppressWarnings(stats::cor.test(residual_degree[[pred]][ok], residual_degree$residual_mean_abs_r_to_other_clients[ok], method = "spearman", exact = FALSE)$p.value)
      })
    )

  readr::write_csv(residual_degree, file.path(sens_cfg$output_dir, "check1_residual_comovement_degree_by_client.csv"))
  readr::write_csv(residual_centrality_tests, file.path(sens_cfg$output_dir, "check1_residual_comovement_association_tests.csv"))

  if (isTRUE(sens_cfg$save_plots) && nrow(residual_null) > 0) {
    p_null <- residual_null |>
      dplyr::filter(is.finite(mean_abs_r)) |>
      ggplot2::ggplot(ggplot2::aes(x = mean_abs_r)) +
      ggplot2::geom_histogram(bins = 60) +
      ggplot2::facet_wrap(~selection, scales = "free_y") +
      ggplot2::geom_vline(
        data = residual_summary,
        ggplot2::aes(xintercept = mean_abs_r),
        linewidth = 0.7
      ) +
      ggplot2::labs(
        title = "Stage-residualized Hsp60/10 client co-movement nulls",
        x = "Mean absolute residual pairwise correlation",
        y = "Permutation count"
      ) +
      ggplot2::theme_classic(base_size = 10)

    ggplot2::ggsave(
      file.path(sens_cfg$output_dir, "check1_stage_residualized_comovement_nulls.pdf"),
      p_null,
      width = 7.0,
      height = 4.5,
      units = "in"
    )
  }

  if (isTRUE(sens_cfg$save_plots)) {
    p_resid <- residual_degree |>
      dplyr::filter(is.finite(protein_late_decline_magnitude), is.finite(residual_mean_abs_r_to_other_clients)) |>
      ggplot2::ggplot(ggplot2::aes(x = protein_late_decline_magnitude, y = residual_mean_abs_r_to_other_clients)) +
      ggplot2::geom_point(alpha = 0.75) +
      ggplot2::geom_smooth(method = "lm", se = TRUE, linewidth = 0.7) +
      ggplot2::labs(
        title = "Late-stage decline versus stage-residualized co-movement",
        x = "Protein late-stage decline magnitude",
        y = "Mean absolute residual correlation to other clients"
      ) +
      ggplot2::theme_classic(base_size = 10)

    ggplot2::ggsave(
      file.path(sens_cfg$output_dir, "check1_late_decline_vs_stage_residualized_comovement.pdf"),
      p_resid,
      width = 5.5,
      height = 4.0,
      units = "in"
    )
  }

  list(
    residual_summary = residual_summary,
    within_stage_summary = within_stage_summary,
    residual_degree = residual_degree,
    residual_centrality_tests = residual_centrality_tests
  )
}

############################################################
## 5. CHECK 2: Function-matched client vs non-client mitochondrial proteins
############################################################

module_from_client_class <- function(x) {
  dplyr::case_when(
    stringr::str_detect(x, regex("translation", ignore_case = TRUE)) ~ "Mitochondrial translation",
    stringr::str_detect(x, regex("pyruvate|TCA", ignore_case = TRUE)) ~ "Pyruvate / TCA metabolism",
    stringr::str_detect(x, regex("OXPHOS|ETC|ATP synthase", ignore_case = TRUE)) ~ "OXPHOS / ETC / ATP synthase",
    stringr::str_detect(x, regex("FAO|lipid|fatty", ignore_case = TRUE)) ~ "FAO / lipid metabolism",
    stringr::str_detect(x, regex("proteostasis|quality|chaperone|protease", ignore_case = TRUE)) ~ "Mitochondrial proteostasis / quality control",
    TRUE ~ NA_character_
  )
}

build_function_module_table <- function() {
  client_modules <- all_hsp60_10_client_tbl |>
    dplyr::transmute(
      gene = as.character(gene),
      functional_module = module_from_client_class(as.character(functional_class)),
      module_source = "client_functional_class"
    ) |>
    dplyr::filter(!is.na(functional_module), functional_module != "") |>
    dplyr::distinct(gene, functional_module, .keep_all = TRUE)

  pathway_map <- c(
    Mito_translation_non_Hsp60_10 = "Mitochondrial translation",
    OXPHOS_ETC_non_Hsp60_10 = "OXPHOS / ETC / ATP synthase",
    TCA_pyruvate_metabolism_non_Hsp60_10 = "Pyruvate / TCA metabolism",
    FAO_metabolism_non_Hsp60_10 = "FAO / lipid metabolism",
    Mito_protein_quality_control_non_Hsp60_10 = "Mitochondrial proteostasis / quality control"
  )

  bg_modules <- purrr::imap_dfr(pathway_gene_sets, function(genes, nm) {
    if (!nm %in% names(pathway_map)) return(tibble())
    tibble::tibble(
      gene = as.character(genes),
      functional_module = unname(pathway_map[[nm]]),
      module_source = nm
    )
  }) |>
    dplyr::distinct(gene, functional_module, .keep_all = TRUE)

  dplyr::bind_rows(client_modules, bg_modules) |>
    dplyr::distinct(gene, functional_module, .keep_all = TRUE)
}

run_metric_matched_null <- function(df, metric_col, group_label) {
  df <- df |>
    dplyr::filter(is.finite(.data[[metric_col]]), !is.na(is_client), !is.na(functional_module))

  clients <- df |> dplyr::filter(is_client)
  nonclients <- df |> dplyr::filter(!is_client)

  if (nrow(clients) < sens_cfg$min_clients_per_module ||
      nrow(nonclients) < sens_cfg$min_nonclients_per_module) {
    return(tibble(
      group = group_label,
      metric = metric_col,
      n_clients = nrow(clients),
      n_nonclients = nrow(nonclients),
      observed_client_mean = NA_real_,
      null_nonclient_mean = NA_real_,
      delta_client_vs_matched_nonclient = NA_real_,
      empirical_p_greater = NA_real_,
      n_perm = sens_cfg$n_perm_check2
    ))
  }

  match_cols <- c("functional_module", "abundance_bin")
  match_cols <- match_cols[vapply(match_cols, function(cc) cc %in% names(df) && any(!is.na(df[[cc]])), logical(1))]
  try_cols_list <- list(
    match_cols,
    intersect(match_cols, c("functional_module", "abundance_bin")),
    intersect(match_cols, "functional_module"),
    intersect(match_cols, "abundance_bin"),
    character()
  )

  observed <- mean(clients[[metric_col]], na.rm = TRUE)
  sampler_info <- build_fast_row_sampler(clients, nonclients, try_cols_list)

  n_iter <- sens_cfg$n_perm_check2
  null_means <- numeric(n_iter)
  for (i in seq_len(n_iter)) {
    progress_msg(i, n_iter, paste0("CHECK 2 ", group_label, " / ", metric_col))
    sampled <- sampler_info$sampler()
    null_means[[i]] <- mean(sampled[[metric_col]], na.rm = TRUE)
  }

  tibble(
    group = group_label,
    metric = metric_col,
    n_clients = nrow(clients),
    n_nonclients = nrow(nonclients),
    observed_client_mean = observed,
    null_nonclient_mean = mean(null_means, na.rm = TRUE),
    null_nonclient_sd = stats::sd(null_means, na.rm = TRUE),
    delta_client_vs_matched_nonclient = observed - null_nonclient_mean,
    empirical_p_greater = empirical_p_greater(null_means, observed),
    n_perm = n_iter,
    matched_on = sampler_info$matched_on
  )
}

run_check2 <- function() {
  message("\nCHECK 2: function-matched client vs non-client mitochondrial proteins")

  module_tbl <- build_function_module_table()

  metrics_for_function <- null_input_tbl |>
    dplyr::transmute(
      gene = as.character(gene),
      is_client = as.logical(is_hsp60_10_client),
      protein_late_decline_magnitude = safe_num2(protein_late_decline_magnitude),
      inverse_braak_magnitude = safe_num2(inverse_braak_magnitude),
      pathology_vulnerability_score = safe_num2(pathology_vulnerability_score),
      matching_abundance = safe_num2(matching_abundance),
      abundance_bin = as.character(abundance_bin)
    ) |>
    dplyr::mutate(
      abundance_bin = dplyr::if_else(
        is.na(abundance_bin) & is.finite(matching_abundance),
        paste0("bin_", dplyr::ntile(matching_abundance, 10)),
        abundance_bin
      )
    ) |>
    dplyr::left_join(module_tbl, by = "gene") |>
    dplyr::filter(!is.na(functional_module), functional_module != "")

  module_counts <- metrics_for_function |>
    dplyr::group_by(functional_module) |>
    dplyr::summarise(
      n_client_rows = sum(is_client, na.rm = TRUE),
      n_nonclient_rows = sum(!is_client, na.rm = TRUE),
      n_unique_client_genes = dplyr::n_distinct(gene[is_client]),
      n_unique_nonclient_genes = dplyr::n_distinct(gene[!is_client]),
      .groups = "drop"
    ) |>
    dplyr::arrange(dplyr::desc(n_unique_client_genes + n_unique_nonclient_genes))

  eligible_modules <- module_counts |>
    dplyr::filter(
      n_unique_client_genes >= sens_cfg$min_clients_per_module,
      n_unique_nonclient_genes >= sens_cfg$min_nonclients_per_module
    ) |>
    dplyr::pull(functional_module)

  eligible <- metrics_for_function |>
    dplyr::filter(functional_module %in% eligible_modules)

  metric_cols <- c("protein_late_decline_magnitude", "inverse_braak_magnitude", "pathology_vulnerability_score")

  direct_tests <- purrr::map_dfr(metric_cols, function(metric_col) {
    eligible |>
      dplyr::group_by(functional_module) |>
      dplyr::summarise(
        metric = metric_col,
        n_clients = sum(is_client & is.finite(.data[[metric_col]]), na.rm = TRUE),
        n_nonclients = sum(!is_client & is.finite(.data[[metric_col]]), na.rm = TRUE),
        client_median = safe_median(.data[[metric_col]][is_client]),
        nonclient_median = safe_median(.data[[metric_col]][!is_client]),
        delta_median_client_minus_nonclient = client_median - nonclient_median,
        wilcox_p_greater = safe_wilcox_greater(.data[[metric_col]][is_client], .data[[metric_col]][!is_client]),
        .groups = "drop"
      ) |>
      dplyr::filter(n_clients >= sens_cfg$min_clients_per_module, n_nonclients >= sens_cfg$min_nonclients_per_module)
  }) |>
    dplyr::group_by(metric) |>
    dplyr::mutate(wilcox_fdr = p.adjust(wilcox_p_greater, method = "BH")) |>
    dplyr::ungroup()

  module_matched <- purrr::map_dfr(metric_cols, function(metric_col) {
    purrr::map_dfr(eligible_modules, function(mod) {
      run_metric_matched_null(
        eligible |> dplyr::filter(functional_module == mod),
        metric_col = metric_col,
        group_label = mod
      )
    })
  }) |>
    dplyr::group_by(metric) |>
    dplyr::mutate(empirical_fdr = p.adjust(empirical_p_greater, method = "BH")) |>
    dplyr::ungroup()

  overall_matched <- purrr::map_dfr(metric_cols, function(metric_col) {
    run_metric_matched_null(
      eligible,
      metric_col = metric_col,
      group_label = "overall_function_and_abundance_matched"
    )
  })

  regression_tests <- purrr::map_dfr(metric_cols, function(metric_col) {
    df_fit <- eligible |>
      dplyr::mutate(metric_value = .data[[metric_col]]) |>
      dplyr::distinct(gene, is_client, functional_module, matching_abundance, metric_value, .keep_all = TRUE) |>
      dplyr::filter(is.finite(metric_value), !is.na(functional_module)) |>
      dplyr::mutate(
        client_status = factor(if_else(is_client, "client", "nonclient"), levels = c("nonclient", "client")),
        matching_abundance_z = as.numeric(scale(matching_abundance))
      )

    form <- if (sum(is.finite(df_fit$matching_abundance_z)) >= 20) {
      stats::as.formula("metric_value ~ client_status + functional_module + matching_abundance_z")
    } else {
      stats::as.formula("metric_value ~ client_status + functional_module")
    }

    fit <- tryCatch(stats::lm(form, data = df_fit), error = function(e) NULL)
    if (is.null(fit)) {
      return(tibble(metric = metric_col, term = NA_character_, estimate = NA_real_, p_value = NA_real_, n = nrow(df_fit), formula = deparse(form)))
    }

    broom::tidy(fit) |>
      dplyr::filter(term == "client_statusclient") |>
      dplyr::transmute(metric = metric_col, term, estimate, std_error = std.error, statistic, p_value = p.value, n = nrow(df_fit), formula = deparse(form))
  })

  readr::write_csv(module_tbl, file.path(sens_cfg$output_dir, "check2_gene_to_function_module_map.csv"))
  readr::write_csv(module_counts, file.path(sens_cfg$output_dir, "check2_function_module_counts.csv"))
  readr::write_csv(direct_tests, file.path(sens_cfg$output_dir, "check2_direct_within_module_tests.csv"))
  readr::write_csv(module_matched, file.path(sens_cfg$output_dir, "check2_module_abundance_matched_permutation_tests.csv"))
  readr::write_csv(overall_matched, file.path(sens_cfg$output_dir, "check2_overall_function_abundance_matched_tests.csv"))
  readr::write_csv(regression_tests, file.path(sens_cfg$output_dir, "check2_function_adjusted_regression_tests.csv"))

  if (isTRUE(sens_cfg$save_plots)) {
    p_module <- direct_tests |>
      dplyr::filter(metric == "protein_late_decline_magnitude") |>
      dplyr::mutate(functional_module = forcats::fct_reorder(functional_module, delta_median_client_minus_nonclient)) |>
      ggplot2::ggplot(ggplot2::aes(x = delta_median_client_minus_nonclient, y = functional_module)) +
      ggplot2::geom_vline(xintercept = 0, linewidth = 0.4) +
      ggplot2::geom_point(size = 2) +
      ggplot2::labs(
        title = "Client decline within matched mitochondrial functional modules",
        x = "Median late-stage decline magnitude: client minus non-client",
        y = NULL
      ) +
      ggplot2::theme_classic(base_size = 10)

    ggplot2::ggsave(
      file.path(sens_cfg$output_dir, "check2_function_matched_late_decline_effects.pdf"),
      p_module,
      width = 6.5,
      height = max(3.5, 0.35 * max(1, length(eligible_modules))),
      units = "in"
    )
  }

  list(
    module_counts = module_counts,
    direct_tests = direct_tests,
    module_matched = module_matched,
    overall_matched = overall_matched,
    regression_tests = regression_tests
  )
}

############################################################
## 6. Run checks and write interpretation guide
############################################################

results <- list()

results$check1 <- if (isTRUE(sens_cfg$run_check1)) {
  run_check1()
} else {
  message("CHECK 1 skipped because SENSITIVITY_RUN_CHECK1=FALSE")
  NULL
}

results$check2 <- if (isTRUE(sens_cfg$run_check2)) {
  run_check2()
} else {
  message("CHECK 2 skipped because SENSITIVITY_RUN_CHECK2=FALSE")
  NULL
}

saveRDS(results, file.path(sens_cfg$output_dir, "pre_submission_sensitivity_results.rds"))

interpretation <- c(
  "Pre-submission sensitivity checks: interpretation guide",
  "",
  "CHECK 1: stage-residualized / within-stage Hsp60/10 client co-movement",
  "Positive result:",
  "  Selected strongly late-declining clients retain higher residual co-movement than matched client sets after disease stage is regressed out, and/or within individual disease stages.",
  "  This supports wording that the vulnerable subset is coordinated beyond a simple shared stage effect.",
  "Negative result:",
  "  The late-stage decline result remains intact, but centrality should be framed as a contextual feature of disease-responsive clients rather than independent evidence for a tightly coordinated subnetwork.",
  "",
  "CHECK 2: function-matched client vs non-client mitochondrial vulnerability",
  "Positive result:",
  "  Clients remain more vulnerable than non-client mitochondrial proteins within comparable functional modules and abundance bins.",
  "  This supports wording that client status adds information beyond broad functional/pathway membership.",
  "Negative or mixed result:",
  "  Do not claim clienthood is the unique driver. Say that vulnerable proteins share Hsp60/10 clienthood within AD-sensitive mitochondrial functions, supporting chaperonin-focused follow-up but not proving causality.",
  "",
  "Speed note:",
  "  Fast defaults use 1,000 permutations and skip within-stage permutation nulls. For a final run, set SENSITIVITY_N_PERM=10000 if needed.",
  "",
  "GitHub note:",
  "  This script only writes local aggregated outputs. The GitHub repository changes only if you intentionally copy/add/commit/push this script or its outputs."
)

readr::write_lines(
  interpretation,
  file.path(sens_cfg$output_dir, "interpretation_guide.txt")
)

git_branch <- tryCatch(
  system2(
    "git",
    c("branch", "--show-current"),
    stdout = TRUE,
    stderr = TRUE
  ),
  error = function(e) NA_character_
)

git_sha <- tryCatch(
  system2(
    "git",
    c("rev-parse", "HEAD"),
    stdout = TRUE,
    stderr = TRUE
  ),
  error = function(e) NA_character_
)

git_status <- tryCatch(
  system2(
    "git",
    c("status", "--short"),
    stdout = TRUE,
    stderr = TRUE
  ),
  error = function(e) NA_character_
)

provenance <- c(
  "R/92 pre-submission sensitivity provenance",
  paste0("generated_at: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
  paste0("git_branch: ", paste(git_branch, collapse = " ")),
  paste0("git_sha: ", paste(git_sha, collapse = " ")),
  paste0(
    "working_tree_dirty: ",
    ifelse(
      length(git_status) > 0 && any(nzchar(git_status)),
      "TRUE",
      "FALSE"
    )
  ),
  "primary_stage_source: prot_meta_adj$clinical_stage",
  "primary_stage_definition: NCI / MCI / AD = cogdx 1 / 2 / 4",
  paste0("random_seed: ", sensitivity_seed),
  paste0("check1_permutations: ", sens_cfg$n_perm_check1),
  paste0("check2_permutations: ", sens_cfg$n_perm_check2),
  paste0(
    "within_stage_nulls: ",
    sens_cfg$run_within_stage_nulls
  ),
  "late_decline_metric: protein_late_decline_magnitude"
)

writeLines(
  provenance,
  file.path(
    sens_cfg$output_dir,
    "sensitivity_provenance.txt"
  )
)

capture.output(
  sessionInfo(),
  file = file.path(
    sens_cfg$output_dir,
    "sensitivity_sessionInfo.txt"
  )
)

message("\nDone. Sensitivity outputs written to: ", sens_cfg$output_dir)
message("Review interpretation_guide.txt before deciding whether to include these results in the manuscript.")
